{{- if .Values.enableConfigMap }}
apiVersion: v1
kind: ConfigMap
{{- end }}
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head><title>NGINX Secret Info</title></head>
    <body>
    <h1>NGINX Secret Info</h1>
    <p>Username: {{ .Values.secret.username }}</p>
    <p>Password: {{ .Values.secret.password }}</p>
    </body>
    </html>
